### ISSUE TITLE
INFO:matplotlib.font_manager:Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.

### ISSUE THREAD

**Issue by monajalal** [murthylab/sleap#383] opened 2020-07-21 22:14 UTC
```
(sleap_env) mona@mona:~/research/animal_pose/sleap$ sleap-label
2020-07-21 18:12:33.936867: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-07-21 18:12:33.936929: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-07-21 18:12:33.936937: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
INFO:matplotlib.font_manager:Generating new fontManager, this may take some time...
INFO:matplotlib.font_manager:Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.

```

^ This error doesn't happen in development version (1.0.8)

**Comment by talmo** [comment] 2020-07-22 13:06
Hi @monajalal,

So this looks like a matplotlib font cache generation issue, possibly addressed by importing matplotlib again or by following [some of these suggestions](https://stackoverflow.com/questions/42097053/matplotlib-cannot-find-basic-fonts).

If it gets solved by installing a different version of sleap, it's possible that either the font cache was re-generated from the first run (I believe the font cache is shared system-wide), or that a new version of matplotlib was installed that could deal with the font file on your system.

If it's the latter, we could pin the minimum matplotlib version, but we'd need more info from you since we haven't been able to reproduce this:

1. What OS and version are you on?
2. Did you install sleap through pip or conda?
3. What version of matplotlib were you on before and which one are you on now?


Since the dev versions seems to work for you, I'll close this issue but feel free to re-open if you'd like to provide the info above and we can try to reproduce it.

**Closed by talmo** 2020-07-22 13:06 UTC
