### ISSUE TITLE
Issues with cattr?

### ISSUE THREAD

**Issue by rojasgabriel** [murthylab/sleap#575] opened 2021-07-29 16:10 UTC
Hello! I'm trying to run the labeling GUI, but I keep getting this error. I've found that I can fix this by updating cattr to the latest version, but then it says that SLEAP is incompatible with that version. Any help would be apprecciated. I'm running it on Mac and installed using conda.

(sleap) Gabriel-Rojas:~ gabrielrojas$ sleap-label
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/sleap-label", line 5, in <module>
    from sleap.gui.app import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sleap/__init__.py", line 9, in <module>
    from sleap.io.dataset import Labels, load_file
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sleap/io/dataset.py", line 58, in <module>
    import cattr
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cattr/_compat.py", line 86, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py)

**Comment by ariematsliah-princeton** [comment] 2021-07-30 12:17
Hi @rojasgabriel 
Not sure if the issue is specific to Mac but in general running Sleap on Mac is not a smooth experience unfortunately. What OS version and hardware do you use? Is it m1 or intel?
Can you please try creating a new conda env with Python 3.6? See https://sleap.ai/installation.html#linux-and-macos-x 

Thanks

**Comment by rojasgabriel** [comment] 2021-07-30 15:56
Hi @ariematsliah-princeton 
I'm using a MacBook Air (Early 2015) with an Intel i5 running on macOS Big Sur 11.4.

I did follow the instructions on the SLEAP page and created the conda environment using py 3.6. What I don't know is why when I run `sleap-label` within the 3.6 conda environment, it's going to a directory where I have 3.8 installed.

**Comment by talmo** [comment] 2021-08-02 17:12
Hi @rojasgabriel,

Just following up here, can you try reinstalling SLEAP in your environment? So like:

```
conda activate sleap
pip install --upgrade sleap
```

also, after activating the environment, try this:
```
which pip
```
This should print a path that goes to where you have Anaconda installed.

One more thing to try would be to uninstall the version in the system Python:
```
conda deactivate
pip uninstall sleap
```

Let me know if any of that works for you.

Cheers,

Talmo

**Comment by rojasgabriel** [comment] 2021-08-02 21:24
Hi @talmo,

None of that fixed the issue. I reinstalled conda and sleap from scratch, but I keep getting the same error (just with a different path).

**Comment by talmo** [comment] 2021-08-02 23:08
Hi @rojasgabriel,

I think several components of SLEAP will break on Python 3.8 (3.7 will work though). We need to see how we can get Python <= 3.7 installed on your system, which is typically taken care of by Anaconda.

Do you mind sharing the console output from `which python`, `which conda` and `which sleap-label` (after doing `conda activate sleap`)?

Thanks!

**Comment by rojasgabriel** [comment] 2021-08-03 17:35
Hi @talmo,

I managed to fix the issue when I tried reinstalling Anaconda from scratch. It appears something was off, but it's fixed now!

Here is the output you asked for:
(base) Gabriel-Rojas:~ gabrielrojas$ conda activate sleap
(sleap) Gabriel-Rojas:~ gabrielrojas$ which python
/Users/gabrielrojas/opt/anaconda3/envs/sleap/bin/python
(sleap) Gabriel-Rojas:~ gabrielrojas$ which conda
/Users/gabrielrojas/opt/anaconda3/condabin/conda
(sleap) Gabriel-Rojas:~ gabrielrojas$ which sleap-label
/Users/gabrielrojas/opt/anaconda3/envs/sleap/bin/sleap-label
(sleap) Gabriel-Rojas:~ gabrielrojas$

**Comment by talmo** [comment] 2021-08-03 17:59
Great to hear! I'll close this for now but feel free to let us know if you're running into any other issues.

**Closed by talmo** 2021-08-03 17:59 UTC
